"""
Manual JR phase graphic renderer.

Uses the SAME modules/assets already used by LiveScore_JR:
- Canva page 1 export via canva_page_one.py
- exact phase compositor via portrait_graphics.py
- Canva token refresh + GitHub secret rotation via juve_bot_espn.py
- Telegram delivery to Bot JR via the existing bot helper

Nothing is generated by AI.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

import canva_page_one
import portrait_graphics
import juve_bot_espn as bot


VALID_KINDS = {"full", "half", "end_of_90"}


def env(name: str, default: str) -> str:
    value = os.getenv(name)
    return default if value is None or value.strip() == "" else value.strip()


def env_int(name: str, default: int) -> int:
    try:
        return int(env(name, str(default)))
    except ValueError as exc:
        raise ValueError(f"{name} deve essere un numero intero") from exc


def truthy(value: str) -> bool:
    return value.strip().lower() in {"1", "true", "yes", "on"}


def safe_name(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_") or "team"


def label_for(kind: str) -> str:
    return {
        "full": "FULL TIME",
        "half": "HALF TIME",
        "end_of_90": "END OF 90’",
    }[kind]


def main() -> None:
    kind = env("PHASE_KIND", "full").lower()
    if kind not in VALID_KINDS:
        raise ValueError(
            f"PHASE_KIND non valido: {kind}. Valori ammessi: "
            + ", ".join(sorted(VALID_KINDS))
        )

    home_name = env("HOME_NAME", "Sassuolo")
    away_name = env("AWAY_NAME", "Juventus")
    home_id = env("HOME_ID", "3997")
    away_id = env("AWAY_ID", "111")
    home_goals = env_int("HOME_GOALS", 3)
    away_goals = env_int("AWAY_GOALS", 2)

    # Per Sassuolo-Juve la Juve è in trasferta, quindi il tema corretto
    # del bot è "away" (rosa). Puoi cambiarlo dal workflow.
    kit = env("KIT", "away").lower()
    if kit not in {"home", "away", "third"}:
        raise ValueError("KIT deve essere home, away oppure third")

    competition = env("COMPETITION", "Serie A")
    send_to_bot_jr = truthy(env("SEND_TO_BOT_JR", "true"))

    print(
        f"JR MANUAL GRAPHIC | {kind=} | "
        f"{home_name} {home_goals}-{away_goals} {away_name} | "
        f"{kit=} | {competition=}",
        flush=True,
    )

    # Riusa esattamente il sistema Canva del bot.
    # get_valid_token() gestisce anche l'eventuale rotazione del refresh token
    # e prova ad aggiornare CANVA_REFRESH_TOKEN nei GitHub Secrets.
    access_token = bot.get_valid_token()
    if not access_token:
        raise RuntimeError(
            "Impossibile ottenere un access token Canva. "
            "Controlla CANVA_CLIENT_ID, CANVA_CLIENT_SECRET e CANVA_REFRESH_TOKEN."
        )

    cache_dir = Path(".state/manual_canva_page_one")
    layers = canva_page_one.export_page_one(
        bot.SESSION,
        access_token,
        bot.CANVA_DESIGN_ID,
        cache_dir,
    )

    # Usa il compositor APPROVATO del repo.
    # Per full/half/end_of_90 prende:
    # background.png + player.png dal PDF Canva appena esportato,
    # poi applica frame, texture, titolo, punteggio, loghi e JR del bot.
    png_bytes = portrait_graphics.phase(
        kind=kind,
        home_name=home_name,
        away_name=away_name,
        home_id=home_id,
        away_id=away_id,
        home_goals=home_goals,
        away_goals=away_goals,
        kit=kit,
        competition=competition,
        layers=layers,
    )

    output_dir = Path("manual_output")
    output_dir.mkdir(parents=True, exist_ok=True)

    filename = (
        f"{kind}_{safe_name(home_name)}_{home_goals}-"
        f"{away_goals}_{safe_name(away_name)}.png"
    )
    output_path = output_dir / filename
    output_path.write_bytes(png_bytes)

    print(f"Grafica salvata: {output_path}", flush=True)

    if send_to_bot_jr:
        caption = os.getenv("CAPTION", "").strip()
        if not caption:
            caption = (
                f"<b>{label_for(kind)}</b>\n\n"
                f"{home_name} {home_goals}-{away_goals} {away_name}"
            )

        ok = bot.send_telegram_with_photo(caption, png_bytes)
        if not ok:
            raise RuntimeError("Invio della grafica a Bot JR fallito")

        print("Grafica inviata a Bot JR.", flush=True)


if __name__ == "__main__":
    main()
