name: Juventus Bot LiveScore Alternative
 
on:
  workflow_dispatch:
 
jobs:
  live-score:
    runs-on: ubuntu-latest
    timeout-minutes: 200
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
 
      - name: Install dependencies
        run: |
          pip install requests pillow pynacl playwright
          playwright install chromium
          playwright install-deps chromium
 
      - name: Run Live Score Bot
        env:
          TELEGRAM_TOKEN:       ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO:          ${{ secrets.TELEGRAM_TO }}
          GH_PAT:               ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY:    ${{ github.repository }}
          GIST_ID:              ${{ secrets.GIST_ID }}
          CANVA_CLIENT_ID:      ${{ secrets.CANVA_CLIENT_ID }}
          CANVA_CLIENT_SECRET:  ${{ secrets.CANVA_CLIENT_SECRET }}
          CANVA_REFRESH_TOKEN:  ${{ secrets.CANVA_REFRESH_TOKEN }}
        run: python juve_bot_alternative.py
