name: Juventus Live Score

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: juve-live-bot
  cancel-in-progress: false

jobs:
  run-live:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v5

      - name: Configura Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Installa librerie
        run: |
          python -m pip install --upgrade pip
          pip install requests pynacl

      - name: Avvia Juventus Live Score e Invio Grafica
        env:
          FOOTBALL_API_KEY: ${{ secrets.API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          CANVA_CLIENT_ID: ${{ secrets.CANVA_CLIENT_ID }}
          CANVA_CLIENT_SECRET: ${{ secrets.CANVA_CLIENT_SECRET }}
          CANVA_REFRESH_TOKEN: ${{ secrets.CANVA_REFRESH_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ONLY_REFRESH_TOKEN: ${{ env.ONLY_REFRESH_TOKEN }} 
        run: python juve_bot.py
