name: Test Bot Telegram (Simulazione)

on:
  workflow_dispatch: # Abilita il bottone manuale

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Configurazione Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Corretto: prima c'era un refuso "python-python"

    - name: Installazione Librerie Requisite
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Esecuzione Script di Test
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      run: python test.py
