name: Test Istantaneo Bot

on:
  workflow_dispatch: # Questo abilita il bottone manuale su GitHub

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Avvia il Test
      run: python -u test_live.py
